services:
  bank-frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - go-backend

  go-backend:
    build: ./bank-backend
    ports:
      - "8080:8080"

volumes:
  mysql-data:
