version: '3.8'

services:
  php-frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/var/www/html
    depends_on:
      - go-backend

  go-backend:
    build: ./backend
    ports:
      - "8080:8080"

volumes:
  mysql-data:
