services:
  db:
    image: mysql:latest
    container_name: mysqlChallege
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: ghost
      MYSQL_PASSWORD: ghost
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data:

