// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	accountFieldNames          = builder.RawFieldNames(&Account{})
	accountRows                = strings.Join(accountFieldNames, ",")
	accountRowsExpectAutoSet   = strings.Join(stringx.Remove(accountFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	accountRowsWithPlaceHolder = strings.Join(stringx.Remove(accountFieldNames, "`account_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankAccountAccountIdPrefix = "cache:bank:account:accountId:"
)

type (
	accountModel interface {
		Insert(ctx context.Context, data *Account) (sql.Result, error)
		FindOne(ctx context.Context, accountId int64) (*Account, error)
		Update(ctx context.Context, data *Account) error
		Delete(ctx context.Context, accountId int64) error
	}

	defaultAccountModel struct {
		sqlc.CachedConn
		table string
	}

	Account struct {
		AccountId  int64  `db:"account_id"`
		DistrictId int64  `db:"district_id"`
		Frequency  string `db:"frequency"`
		Date       int64  `db:"date"`
	}
)

func newAccountModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAccountModel {
	return &defaultAccountModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`account`",
	}
}

func (m *defaultAccountModel) Delete(ctx context.Context, accountId int64) error {
	bankAccountAccountIdKey := fmt.Sprintf("%s%v", cacheBankAccountAccountIdPrefix, accountId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `account_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, accountId)
	}, bankAccountAccountIdKey)
	return err
}

func (m *defaultAccountModel) FindOne(ctx context.Context, accountId int64) (*Account, error) {
	bankAccountAccountIdKey := fmt.Sprintf("%s%v", cacheBankAccountAccountIdPrefix, accountId)
	var resp Account
	err := m.QueryRowCtx(ctx, &resp, bankAccountAccountIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `account_id` = ? limit 1", accountRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, accountId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAccountModel) Insert(ctx context.Context, data *Account) (sql.Result, error) {
	bankAccountAccountIdKey := fmt.Sprintf("%s%v", cacheBankAccountAccountIdPrefix, data.AccountId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, accountRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.AccountId, data.DistrictId, data.Frequency, data.Date)
	}, bankAccountAccountIdKey)
	return ret, err
}

func (m *defaultAccountModel) Update(ctx context.Context, data *Account) error {
	bankAccountAccountIdKey := fmt.Sprintf("%s%v", cacheBankAccountAccountIdPrefix, data.AccountId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `account_id` = ?", m.table, accountRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DistrictId, data.Frequency, data.Date, data.AccountId)
	}, bankAccountAccountIdKey)
	return err
}

func (m *defaultAccountModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankAccountAccountIdPrefix, primary)
}

func (m *defaultAccountModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `account_id` = ? limit 1", accountRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAccountModel) tableName() string {
	return m.table
}
