// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	cardFieldNames          = builder.RawFieldNames(&Card{})
	cardRows                = strings.Join(cardFieldNames, ",")
	cardRowsExpectAutoSet   = strings.Join(stringx.Remove(cardFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	cardRowsWithPlaceHolder = strings.Join(stringx.Remove(cardFieldNames, "`card_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankCardCardIdPrefix = "cache:bank:card:cardId:"
)

type (
	cardModel interface {
		Insert(ctx context.Context, data *Card) (sql.Result, error)
		FindOne(ctx context.Context, cardId int64) (*Card, error)
		Update(ctx context.Context, data *Card) error
		Delete(ctx context.Context, cardId int64) error
	}

	defaultCardModel struct {
		sqlc.CachedConn
		table string
	}

	Card struct {
		CardId int64  `db:"card_id"`
		DispId int64  `db:"disp_id"`
		Type   string `db:"type"`
		Issued string `db:"issued"`
	}
)

func newCardModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCardModel {
	return &defaultCardModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`card`",
	}
}

func (m *defaultCardModel) Delete(ctx context.Context, cardId int64) error {
	bankCardCardIdKey := fmt.Sprintf("%s%v", cacheBankCardCardIdPrefix, cardId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `card_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, cardId)
	}, bankCardCardIdKey)
	return err
}

func (m *defaultCardModel) FindOne(ctx context.Context, cardId int64) (*Card, error) {
	bankCardCardIdKey := fmt.Sprintf("%s%v", cacheBankCardCardIdPrefix, cardId)
	var resp Card
	err := m.QueryRowCtx(ctx, &resp, bankCardCardIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `card_id` = ? limit 1", cardRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, cardId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCardModel) Insert(ctx context.Context, data *Card) (sql.Result, error) {
	bankCardCardIdKey := fmt.Sprintf("%s%v", cacheBankCardCardIdPrefix, data.CardId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, cardRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CardId, data.DispId, data.Type, data.Issued)
	}, bankCardCardIdKey)
	return ret, err
}

func (m *defaultCardModel) Update(ctx context.Context, data *Card) error {
	bankCardCardIdKey := fmt.Sprintf("%s%v", cacheBankCardCardIdPrefix, data.CardId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `card_id` = ?", m.table, cardRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DispId, data.Type, data.Issued, data.CardId)
	}, bankCardCardIdKey)
	return err
}

func (m *defaultCardModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankCardCardIdPrefix, primary)
}

func (m *defaultCardModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `card_id` = ? limit 1", cardRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCardModel) tableName() string {
	return m.table
}
