// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clientFieldNames          = builder.RawFieldNames(&Client{})
	clientRows                = strings.Join(clientFieldNames, ",")
	clientRowsExpectAutoSet   = strings.Join(stringx.Remove(clientFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	clientRowsWithPlaceHolder = strings.Join(stringx.Remove(clientFieldNames, "`client_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankClientClientIdPrefix = "cache:bank:client:clientId:"
)

type (
	clientModel interface {
		Insert(ctx context.Context, data *Client) (sql.Result, error)
		FindOne(ctx context.Context, clientId int64) (*Client, error)
		Update(ctx context.Context, data *Client) error
		Delete(ctx context.Context, clientId int64) error
	}

	defaultClientModel struct {
		sqlc.CachedConn
		table string
	}

	Client struct {
		ClientId    int64 `db:"client_id"`
		DistrictId  int64 `db:"district_id"`
		BirthNumber int64 `db:"birth_number"`
	}
)

func newClientModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultClientModel {
	return &defaultClientModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`client`",
	}
}

func (m *defaultClientModel) Delete(ctx context.Context, clientId int64) error {
	bankClientClientIdKey := fmt.Sprintf("%s%v", cacheBankClientClientIdPrefix, clientId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `client_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, clientId)
	}, bankClientClientIdKey)
	return err
}

func (m *defaultClientModel) FindOne(ctx context.Context, clientId int64) (*Client, error) {
	bankClientClientIdKey := fmt.Sprintf("%s%v", cacheBankClientClientIdPrefix, clientId)
	var resp Client
	err := m.QueryRowCtx(ctx, &resp, bankClientClientIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `client_id` = ? limit 1", clientRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, clientId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientModel) Insert(ctx context.Context, data *Client) (sql.Result, error) {
	bankClientClientIdKey := fmt.Sprintf("%s%v", cacheBankClientClientIdPrefix, data.ClientId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, clientRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.ClientId, data.DistrictId, data.BirthNumber)
	}, bankClientClientIdKey)
	return ret, err
}

func (m *defaultClientModel) Update(ctx context.Context, data *Client) error {
	bankClientClientIdKey := fmt.Sprintf("%s%v", cacheBankClientClientIdPrefix, data.ClientId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `client_id` = ?", m.table, clientRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DistrictId, data.BirthNumber, data.ClientId)
	}, bankClientClientIdKey)
	return err
}

func (m *defaultClientModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankClientClientIdPrefix, primary)
}

func (m *defaultClientModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `client_id` = ? limit 1", clientRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultClientModel) tableName() string {
	return m.table
}
