// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dispFieldNames          = builder.RawFieldNames(&Disp{})
	dispRows                = strings.Join(dispFieldNames, ",")
	dispRowsExpectAutoSet   = strings.Join(stringx.Remove(dispFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dispRowsWithPlaceHolder = strings.Join(stringx.Remove(dispFieldNames, "`disp_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankDispDispIdPrefix = "cache:bank:disp:dispId:"
)

type (
	dispModel interface {
		Insert(ctx context.Context, data *Disp) (sql.Result, error)
		FindOne(ctx context.Context, dispId int64) (*Disp, error)
		Update(ctx context.Context, data *Disp) error
		Delete(ctx context.Context, dispId int64) error
	}

	defaultDispModel struct {
		sqlc.CachedConn
		table string
	}

	Disp struct {
		DispId    int64  `db:"disp_id"`
		ClientId  int64  `db:"client_id"`
		AccountId int64  `db:"account_id"`
		Type      string `db:"type"`
	}
)

func newDispModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDispModel {
	return &defaultDispModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`disp`",
	}
}

func (m *defaultDispModel) Delete(ctx context.Context, dispId int64) error {
	bankDispDispIdKey := fmt.Sprintf("%s%v", cacheBankDispDispIdPrefix, dispId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `disp_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, dispId)
	}, bankDispDispIdKey)
	return err
}

func (m *defaultDispModel) FindOne(ctx context.Context, dispId int64) (*Disp, error) {
	bankDispDispIdKey := fmt.Sprintf("%s%v", cacheBankDispDispIdPrefix, dispId)
	var resp Disp
	err := m.QueryRowCtx(ctx, &resp, bankDispDispIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `disp_id` = ? limit 1", dispRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, dispId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDispModel) Insert(ctx context.Context, data *Disp) (sql.Result, error) {
	bankDispDispIdKey := fmt.Sprintf("%s%v", cacheBankDispDispIdPrefix, data.DispId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?)", m.table, dispRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DispId, data.ClientId, data.AccountId, data.Type)
	}, bankDispDispIdKey)
	return ret, err
}

func (m *defaultDispModel) Update(ctx context.Context, data *Disp) error {
	bankDispDispIdKey := fmt.Sprintf("%s%v", cacheBankDispDispIdPrefix, data.DispId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `disp_id` = ?", m.table, dispRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ClientId, data.AccountId, data.Type, data.DispId)
	}, bankDispDispIdKey)
	return err
}

func (m *defaultDispModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankDispDispIdPrefix, primary)
}

func (m *defaultDispModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `disp_id` = ? limit 1", dispRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDispModel) tableName() string {
	return m.table
}
