// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	districtFieldNames          = builder.RawFieldNames(&District{})
	districtRows                = strings.Join(districtFieldNames, ",")
	districtRowsExpectAutoSet   = strings.Join(stringx.Remove(districtFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	districtRowsWithPlaceHolder = strings.Join(stringx.Remove(districtFieldNames, "`district_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankDistrictDistrictIdPrefix = "cache:bank:district:districtId:"
)

type (
	districtModel interface {
		Insert(ctx context.Context, data *District) (sql.Result, error)
		FindOne(ctx context.Context, districtId int64) (*District, error)
		Update(ctx context.Context, data *District) error
		Delete(ctx context.Context, districtId int64) error
	}

	defaultDistrictModel struct {
		sqlc.CachedConn
		table string
	}

	District struct {
		DistrictId   int64   `db:"district_id"`
		DistrictName string  `db:"district_name"`
		Region       string  `db:"region"`
		A4           int64   `db:"A4"`
		A5           int64   `db:"A5"`
		A6           int64   `db:"A6"`
		A7           int64   `db:"A7"`
		A8           int64   `db:"A8"`
		A9           int64   `db:"A9"`
		A10          float64 `db:"A10"`
		A11          int64   `db:"A11"`
		A12          float64 `db:"A12"`
		A13          float64 `db:"A13"`
		A14          int64   `db:"A14"`
		A15          int64   `db:"A15"`
		A16          int64   `db:"A16"`
	}
)

func newDistrictModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDistrictModel {
	return &defaultDistrictModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`district`",
	}
}

func (m *defaultDistrictModel) Delete(ctx context.Context, districtId int64) error {
	bankDistrictDistrictIdKey := fmt.Sprintf("%s%v", cacheBankDistrictDistrictIdPrefix, districtId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `district_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, districtId)
	}, bankDistrictDistrictIdKey)
	return err
}

func (m *defaultDistrictModel) FindOne(ctx context.Context, districtId int64) (*District, error) {
	bankDistrictDistrictIdKey := fmt.Sprintf("%s%v", cacheBankDistrictDistrictIdPrefix, districtId)
	var resp District
	err := m.QueryRowCtx(ctx, &resp, bankDistrictDistrictIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `district_id` = ? limit 1", districtRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, districtId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDistrictModel) Insert(ctx context.Context, data *District) (sql.Result, error) {
	bankDistrictDistrictIdKey := fmt.Sprintf("%s%v", cacheBankDistrictDistrictIdPrefix, data.DistrictId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, districtRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DistrictId, data.DistrictName, data.Region, data.A4, data.A5, data.A6, data.A7, data.A8, data.A9, data.A10, data.A11, data.A12, data.A13, data.A14, data.A15, data.A16)
	}, bankDistrictDistrictIdKey)
	return ret, err
}

func (m *defaultDistrictModel) Update(ctx context.Context, data *District) error {
	bankDistrictDistrictIdKey := fmt.Sprintf("%s%v", cacheBankDistrictDistrictIdPrefix, data.DistrictId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `district_id` = ?", m.table, districtRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DistrictName, data.Region, data.A4, data.A5, data.A6, data.A7, data.A8, data.A9, data.A10, data.A11, data.A12, data.A13, data.A14, data.A15, data.A16, data.DistrictId)
	}, bankDistrictDistrictIdKey)
	return err
}

func (m *defaultDistrictModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankDistrictDistrictIdPrefix, primary)
}

func (m *defaultDistrictModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `district_id` = ? limit 1", districtRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultDistrictModel) tableName() string {
	return m.table
}
