// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	loanFieldNames          = builder.RawFieldNames(&Loan{})
	loanRows                = strings.Join(loanFieldNames, ",")
	loanRowsExpectAutoSet   = strings.Join(stringx.Remove(loanFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	loanRowsWithPlaceHolder = strings.Join(stringx.Remove(loanFieldNames, "`loan_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankLoanLoanIdPrefix = "cache:bank:loan:loanId:"
)

type (
	loanModel interface {
		Insert(ctx context.Context, data *Loan) (sql.Result, error)
		FindOne(ctx context.Context, loanId int64) (*Loan, error)
		Update(ctx context.Context, data *Loan) error
		Delete(ctx context.Context, loanId int64) error
	}

	defaultLoanModel struct {
		sqlc.CachedConn
		table string
	}

	Loan struct {
		LoanId    int64   `db:"loan_id"`
		AccountId int64   `db:"account_id"`
		Date      int64   `db:"date"`
		Amount    int64   `db:"amount"`
		Duration  int64   `db:"duration"`
		Payments  float64 `db:"payments"`
		Status    string  `db:"status"`
	}
)

func newLoanModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultLoanModel {
	return &defaultLoanModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`loan`",
	}
}

func (m *defaultLoanModel) Delete(ctx context.Context, loanId int64) error {
	bankLoanLoanIdKey := fmt.Sprintf("%s%v", cacheBankLoanLoanIdPrefix, loanId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `loan_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, loanId)
	}, bankLoanLoanIdKey)
	return err
}

func (m *defaultLoanModel) FindOne(ctx context.Context, loanId int64) (*Loan, error) {
	bankLoanLoanIdKey := fmt.Sprintf("%s%v", cacheBankLoanLoanIdPrefix, loanId)
	var resp Loan
	err := m.QueryRowCtx(ctx, &resp, bankLoanLoanIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `loan_id` = ? limit 1", loanRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, loanId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultLoanModel) Insert(ctx context.Context, data *Loan) (sql.Result, error) {
	bankLoanLoanIdKey := fmt.Sprintf("%s%v", cacheBankLoanLoanIdPrefix, data.LoanId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?)", m.table, loanRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.LoanId, data.AccountId, data.Date, data.Amount, data.Duration, data.Payments, data.Status)
	}, bankLoanLoanIdKey)
	return ret, err
}

func (m *defaultLoanModel) Update(ctx context.Context, data *Loan) error {
	bankLoanLoanIdKey := fmt.Sprintf("%s%v", cacheBankLoanLoanIdPrefix, data.LoanId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `loan_id` = ?", m.table, loanRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AccountId, data.Date, data.Amount, data.Duration, data.Payments, data.Status, data.LoanId)
	}, bankLoanLoanIdKey)
	return err
}

func (m *defaultLoanModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankLoanLoanIdPrefix, primary)
}

func (m *defaultLoanModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `loan_id` = ? limit 1", loanRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultLoanModel) tableName() string {
	return m.table
}
