// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	transFieldNames          = builder.RawFieldNames(&Trans{})
	transRows                = strings.Join(transFieldNames, ",")
	transRowsExpectAutoSet   = strings.Join(stringx.Remove(transFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	transRowsWithPlaceHolder = strings.Join(stringx.Remove(transFieldNames, "`trans_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheBankTransTransIdPrefix = "cache:bank:trans:transId:"
)

type (
	transModel interface {
		Insert(ctx context.Context, data *Trans) (sql.Result, error)
		FindOne(ctx context.Context, transId int64) (*Trans, error)
		Update(ctx context.Context, data *Trans) error
		Delete(ctx context.Context, transId int64) error
	}

	defaultTransModel struct {
		sqlc.CachedConn
		table string
	}

	Trans struct {
		TransId   int64   `db:"trans_id"`
		AccountId int64   `db:"account_id"`
		Date      int64   `db:"date"`
		Type      string  `db:"type"`
		Operation string  `db:"operation"`
		Amount    float64 `db:"amount"`
		Balance   float64 `db:"balance"`
		KSymbol   string  `db:"k_symbol"`
		Bank      string  `db:"bank"`
		Account   int64   `db:"account"`
	}
)

func newTransModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultTransModel {
	return &defaultTransModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`trans`",
	}
}

func (m *defaultTransModel) Delete(ctx context.Context, transId int64) error {
	bankTransTransIdKey := fmt.Sprintf("%s%v", cacheBankTransTransIdPrefix, transId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `trans_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, transId)
	}, bankTransTransIdKey)
	return err
}

func (m *defaultTransModel) FindOne(ctx context.Context, transId int64) (*Trans, error) {
	bankTransTransIdKey := fmt.Sprintf("%s%v", cacheBankTransTransIdPrefix, transId)
	var resp Trans
	err := m.QueryRowCtx(ctx, &resp, bankTransTransIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `trans_id` = ? limit 1", transRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, transId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultTransModel) Insert(ctx context.Context, data *Trans) (sql.Result, error) {
	bankTransTransIdKey := fmt.Sprintf("%s%v", cacheBankTransTransIdPrefix, data.TransId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, transRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.TransId, data.AccountId, data.Date, data.Type, data.Operation, data.Amount, data.Balance, data.KSymbol, data.Bank, data.Account)
	}, bankTransTransIdKey)
	return ret, err
}

func (m *defaultTransModel) Update(ctx context.Context, data *Trans) error {
	bankTransTransIdKey := fmt.Sprintf("%s%v", cacheBankTransTransIdPrefix, data.TransId)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `trans_id` = ?", m.table, transRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.AccountId, data.Date, data.Type, data.Operation, data.Amount, data.Balance, data.KSymbol, data.Bank, data.Account, data.TransId)
	}, bankTransTransIdKey)
	return err
}

func (m *defaultTransModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheBankTransTransIdPrefix, primary)
}

func (m *defaultTransModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `trans_id` = ? limit 1", transRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultTransModel) tableName() string {
	return m.table
}
